# Generated by Django 4.2.27 on 2025-12-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тендера')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('open', 'Идёт приём ставок'), ('closed', 'Завершён')], default='draft', max_length=10, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала торгов')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания торгов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='Город назначения')),
                ('volume', models.PositiveIntegerField(verbose_name='Количество машин (объём)')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стартовая цена')),
                ('current_best_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая лучшая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='core.tender', verbose_name='Тендер')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, создавший ставку')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.direction', verbose_name='Направление')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender', verbose_name='Тендер')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'unique_together': {('tender', 'direction', 'company')},
            },
        ),
    ]
