# Generated by Django 4.2.27 on 2026-01-22 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_direction_final_price_direction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='direction',
            name='final_timer_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание финального таймера'),
        ),
        migrations.AddField(
            model_name='direction',
            name='is_in_rebidding',
            field=models.BooleanField(default=False, verbose_name='Идёт переторжка'),
        ),
        migrations.AddField(
            model_name='direction',
            name='last_bid_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней ставки'),
        ),
        migrations.AddField(
            model_name='direction',
            name='rebidding_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание переторжки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tender',
            name='final_timer_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Время без новых ставок до автоматического закрытия направления', verbose_name='Финальный таймер (минуты)'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('leadership', 'Руководство')], default='manager', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('final_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время определения победителя')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='core.company', verbose_name='Компания')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners_history', to='core.direction', verbose_name='Направление')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='core.tender', verbose_name='Тендер')),
            ],
            options={
                'verbose_name': 'Победитель',
                'verbose_name_plural': 'Победители',
                'unique_together': {('tender', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tender_created', 'Создан тендер'), ('tender_opened', 'Открыт тендер'), ('tender_closed', 'Закрыт тендер'), ('bid_created', 'Создана ставка'), ('bid_updated', 'Обновлена ставка'), ('direction_created', 'Создано направление'), ('company_created', 'Создана компания'), ('user_login', 'Вход в систему'), ('user_logout', 'Выход из системы'), ('report_generated', 'Сгенерирован отчёт')], max_length=50, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит лог',
                'verbose_name_plural': 'Аудит логи',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx')],
            },
        ),
    ]
