# Generated by Django 4.2.27 on 2026-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bid_is_active_bid_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tender', 'direction', 'company', '-created_at'], name='core_bid_tender__28dbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['direction', 'is_active', 'price'], name='core_bid_directi_d22171_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tender', 'direction', 'company'), name='unique_active_bid_per_direction_company'),
        ),
    ]
