# Generated by Django 4.2.27 on 2026-03-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_bid_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата согласия')),
            ],
            options={
                'verbose_name': 'Согласие с условиями',
                'verbose_name_plural': 'Согласия с условиями',
            },
        ),
        migrations.RemoveConstraint(
            model_name='bid',
            name='unique_active_bid_per_direction_company',
        ),
        migrations.AddField(
            model_name='tender',
            name='agreement_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст соглашения для участия (галочка)'),
        ),
        migrations.AddField(
            model_name='tender',
            name='winner_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для победителя'),
        ),
        migrations.AddField(
            model_name='tenderagreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_agreements', to='core.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='tenderagreement',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='core.tender', verbose_name='Тендер'),
        ),
        migrations.AddField(
            model_name='tenderagreement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AlterUniqueTogether(
            name='tenderagreement',
            unique_together={('tender', 'company')},
        ),
    ]
